### ISSUE TITLE
Signature needs to be unique and use of interfaces ?

### ISSUE THREAD

**Issue by iangregsondev** [Wufe/mapper#3]
Hi,

Thanks for a great library, I am trying to figure out if the signature needs to be unique across different createMap or can it use the same signature (symbols) ?

Also when creating maps and actually doing the map, can we use Interfaces ?? As technically these are not transcompiled ?

Thanks in advance

**Comment by wufe** [comment]
Hello,
The signature has to be unique for a given `(source, destination)` pair. So, if you are mapping from S1 to D1 you must use a signature. If you are mapping from S1 to D2, the signature must be different from the previous one.

Interfaces are not supported because typescript interfaces are not transpiled in javascript.

**Comment by iangregsondev** [comment]
ok, thank you.
